# coding: utf-8

"""
    Personal Knowledge Graph API

    A note-based knowledge graph with bi-directional links and tags.

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from datetime import datetime
from pydantic import BaseModel, ConfigDict, StrictInt, StrictStr
from typing import Any, ClassVar, Dict, List
from openapi_client.models.note_summary import NoteSummary
from openapi_client.models.tag_response import TagResponse
from typing import Optional, Set
from typing_extensions import Self
from pydantic_core import to_jsonable_python

class NoteDetailResponse(BaseModel):
    """
    Full note detail as returned by GET /notes/{note_id}. Includes both outgoing links (notes this note points to) and backlinks (notes that point to this note).
    """ # noqa: E501
    id: StrictInt
    title: StrictStr
    content: StrictStr
    created_at: datetime
    tags: List[TagResponse]
    outgoing_links: List[NoteSummary]
    backlinks: List[NoteSummary]
    __properties: ClassVar[List[str]] = ["id", "title", "content", "created_at", "tags", "outgoing_links", "backlinks"]

    model_config = ConfigDict(
        validate_by_name=True,
        validate_by_alias=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(to_jsonable_python(self.to_dict()))

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of NoteDetailResponse from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of each item in tags (list)
        _items = []
        if self.tags:
            for _item_tags in self.tags:
                _items.append(_item_tags.to_dict() if _item_tags is not None else None)
            _dict['tags'] = _items
        # override the default output from pydantic by calling `to_dict()` of each item in outgoing_links (list)
        _items = []
        if self.outgoing_links:
            for _item_outgoing_links in self.outgoing_links:
                _items.append(_item_outgoing_links.to_dict() if _item_outgoing_links is not None else None)
            _dict['outgoing_links'] = _items
        # override the default output from pydantic by calling `to_dict()` of each item in backlinks (list)
        _items = []
        if self.backlinks:
            for _item_backlinks in self.backlinks:
                _items.append(_item_backlinks.to_dict() if _item_backlinks is not None else None)
            _dict['backlinks'] = _items
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of NoteDetailResponse from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "id": obj.get("id"),
            "title": obj.get("title"),
            "content": obj.get("content"),
            "created_at": obj.get("created_at"),
            "tags": [TagResponse.from_dict(_item) for _item in obj["tags"]] if obj.get("tags") is not None else None,
            "outgoing_links": [NoteSummary.from_dict(_item) for _item in obj["outgoing_links"]] if obj.get("outgoing_links") is not None else None,
            "backlinks": [NoteSummary.from_dict(_item) for _item in obj["backlinks"]] if obj.get("backlinks") is not None else None
        })
        return _obj


