# coding: utf-8

"""
    Personal Knowledge Graph API

    A note-based knowledge graph with bi-directional links and tags.

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.api.graph_api import GraphApi


class TestGraphApi(unittest.TestCase):
    """GraphApi unit test stubs"""

    def setUp(self) -> None:
        self.api = GraphApi()

    def tearDown(self) -> None:
        pass

    def test_get_graph_graph_get(self) -> None:
        """Test case for get_graph_graph_get

        Get Graph
        """
        pass


if __name__ == '__main__':
    unittest.main()
