# coding: utf-8

"""
    Personal Knowledge Graph API

    A note-based knowledge graph with bi-directional links and tags.

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.models.note_response import NoteResponse

class TestNoteResponse(unittest.TestCase):
    """NoteResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> NoteResponse:
        """Test NoteResponse
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `NoteResponse`
        """
        model = NoteResponse()
        if include_optional:
            return NoteResponse(
                id = 56,
                title = '',
                content = '',
                created_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'),
                tags = [
                    openapi_client.models.tag_response.TagResponse(
                        id = 56, 
                        name = '', )
                    ]
            )
        else:
            return NoteResponse(
                id = 56,
                title = '',
                content = '',
                created_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'),
                tags = [
                    openapi_client.models.tag_response.TagResponse(
                        id = 56, 
                        name = '', )
                    ],
        )
        """

    def testNoteResponse(self):
        """Test NoteResponse"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
