# coding: utf-8

"""
    Personal Knowledge Graph API

    A note-based knowledge graph with bi-directional links and tags.

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.models.graph_edge import GraphEdge

class TestGraphEdge(unittest.TestCase):
    """GraphEdge unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> GraphEdge:
        """Test GraphEdge
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `GraphEdge`
        """
        model = GraphEdge()
        if include_optional:
            return GraphEdge(
                source_id = 56,
                target_id = 56
            )
        else:
            return GraphEdge(
                source_id = 56,
                target_id = 56,
        )
        """

    def testGraphEdge(self):
        """Test GraphEdge"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
