# coding: utf-8

"""
    Personal Knowledge Graph API

    A note-based knowledge graph with bi-directional links and tags.

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.models.note_create import NoteCreate

class TestNoteCreate(unittest.TestCase):
    """NoteCreate unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> NoteCreate:
        """Test NoteCreate
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `NoteCreate`
        """
        model = NoteCreate()
        if include_optional:
            return NoteCreate(
                title = '',
                content = '',
                tags = [
                    ''
                    ]
            )
        else:
            return NoteCreate(
                title = '',
        )
        """

    def testNoteCreate(self):
        """Test NoteCreate"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
