# coding: utf-8

"""
    Personal Knowledge Graph API

    A note-based knowledge graph with bi-directional links and tags.

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.api.notes_api import NotesApi


class TestNotesApi(unittest.TestCase):
    """NotesApi unit test stubs"""

    def setUp(self) -> None:
        self.api = NotesApi()

    def tearDown(self) -> None:
        pass

    def test_create_note_notes_post(self) -> None:
        """Test case for create_note_notes_post

        Create Note
        """
        pass

    def test_get_note_notes_note_id_get(self) -> None:
        """Test case for get_note_notes_note_id_get

        Get Note
        """
        pass

    def test_link_notes_notes_note_id_link_patch(self) -> None:
        """Test case for link_notes_notes_note_id_link_patch

        Link Notes
        """
        pass

    def test_list_all_tags_notes_tags_all_get(self) -> None:
        """Test case for list_all_tags_notes_tags_all_get

        List All Tags
        """
        pass

    def test_list_notes_notes_get(self) -> None:
        """Test case for list_notes_notes_get

        List Notes
        """
        pass


if __name__ == '__main__':
    unittest.main()
